openapi: 3.0.0
info:
  title: CustomerAPI
  version: '1.0'
  contact:
    name: Dave Roberts
    url: 'https://stoplight.io'
    email: dr@stoplight.io
  license:
    name: MIT
  description: My description
servers:
  - url: 'http://localhost:3000'
tags: null
paths:
  /customers:
    get:
      summary: Get customers
      tags:
        - endpoints
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: 'https://sales.stoplight-dev.com/api/nodes.raw/?srn=gh/stoplightio/foundation-demo/reference/models/todos/todo-full.v2.json&mid=66&deref=bundle'
      operationId: get-customers
      description: customers endpoint
      requestBody:
        content:
          application/json:
            schema:
              $ref: 'https://sales.stoplight-dev.com/api/nodes.raw/?srn=gh/stoplightio/foundation-demo/reference/models/todos/todo-full.v2.json&mid=67&deref=bundle'
        description: ''
      parameters:
        - schema:
            type: string
          in: header
