openapi: 3.0.0
info:
  title: foo
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /bar:
    get:
      summary: get bar
      tags: []
      responses: {}
      operationId: get-bar
components:
  schemas: {}
