openapi: 3.0.0
info:
  title: fooAPI
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /foo:
    get:
      summary: getfoo
      tags: []
      responses:
        '200':
          description: OK
      operationId: get-foo
      description: ''
      parameters: []
      requestBody:
        description: ''
components:
  schemas: {}
