openapi: 3.0.0
info:
  title: myapi
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /stuff:
    get:
      summary: get stuff
      tags: []
      responses:
        '308':
          description: Permanent Redirect (experiemental)
          content:
            application/json:
              schema:
                $ref: ../models/mymodel.v1.yaml
      operationId: get-stuff
components:
  schemas: {}
